### ISSUE TITLE
Will we ever get a mobile Discord client that doesn't get shut down in less than a year?

### ISSUE THREAD

**Issue by Enzic1** [bunny-mod/BunnyManager#29]
It's embarrassing how weak-willed developers are becoming nowadays. What a joke.

**Comment by Arxari** [comment]
Wtf

**Comment by Gabe-W-J** [comment]
???? have some empathy wtf

**Comment by yasscaleb** [comment]
open source devopers are usually unpaid and usually do projects as a hobby, they owe you nothing

**Comment by Arxari** [comment]
Ah yes, struggling to survive in a bloodthirsty economy and society. How weak willed are they its shameful

**Comment by yasscaleb** [comment]
don't treat developers like crap

**Comment by breadcat0314** [comment]
Ah yes, let’s all attack someone who was doing this project asking for nothing in return. I have much respect for anyone who develops for this community and can take this kind of disrespect

**Comment by Arxari** [comment]
Yeah, the one thing I hate about open source is just how toxic the community can get when a project stops being maintained

**Comment by Saarker** [comment]
what an embarrassing excuse of a person you are

**Comment by NotAShelf** [comment]
Keep in mind that this person is either
- 13
- 13 and a troll

You're feeding the troll.

**Comment by Gabe-W-J** [comment]
all take no give

**Comment by h4rldev** [comment]
Make your own lol

**Comment by Arxari** [comment]
closed as not planned :skull: 

XD
