### ISSUE TITLE
[Request] Add option to have two different Bunny installs

### ISSUE THREAD

**Issue by cursedastronaut** [bunny-mod/BunnyManager#35]
It would be nice to be able, for secondary accounts, to also be able to use Bunny without using work mode or a whole another user. In the Manager, you could rename the app, but also its identifier (com.discordapp.discord for instance) so that you can have two separate Bunny installs. I kept Vendetta for my other account, but now it's broken.

It'd be great!

**Comment by castdrian** [comment]
for alts you can just use the native account switcher, for multiple installs all you have to do is change the bundle id in the settings

**Comment by cursedastronaut** [comment]
I can't seem to find the bundle ID setting in the app... Also, the native account switcher ? On Mobile?

**Comment by cursedastronaut** [comment]
Any help?

**Comment by cursedastronaut** [comment]
Any help?

**Comment by AToska21** [comment]
Bunny is currently not maintained/paused development. Please see the Discord server for more info.

**Comment by Rairof** [comment]
https://github.com/bunny-mod/BunnyManager/issues/35#issuecomment-2561913618
Incorrect. Bunny is in "maintenance mode". You please see the Discord server for more info:
https://discord.com/channels/1196075698301968455/1205101050739167272/1288213054772871260

**Comment by Rairof** [comment]
https://github.com/bunny-mod/BunnyManager/issues/35#issue-2747165667
Yes, you can have 2 or more seperate bunny installs through bunny manager by changing the package name in developer settings. (Spam click version info in about section to unlock developer settings)

**Comment by AToska21** [comment]
> [#35 (comment)](https://github.com/bunny-mod/BunnyManager/issues/35#issuecomment-2561913618) Incorrect. Bunny is in "maintenance mode". You please see the Discord server for more info: [discord.com/channels/1196075698301968455/1205101050739167272/1288213054772871260](https://discord.com/channels/1196075698301968455/1205101050739167272/1288213054772871260)

🤓 ☝️

**Comment by cursedastronaut** [comment]
> [#35 (comment)](https://github.com/bunny-mod/BunnyManager/issues/35#issue-2747165667) Yes, you can have 2 or more seperate bunny installs through bunny manager by changing the package name in developer settings. (Spam click version info in about section to unlock developer settings)

Thanks! That was very helpful.
